version: '3'

services:
    backend:
        build:
            context: .
            dockerfile: ./backend.DockerFile
        image: role-manager-backend
        ports:
            - "3000:3000"
        #     - "443:443"
        # environment:
        #     - 
        depends_on:
            - 'mongo'

    # MongoDB
    mongo:
        image: 'mongo'
        container_name: mongo
        # ports:
        #     - '27017:27017'
        volumes:
            - ./mongodata:/data/db
        restart: always

    fronend:
        build:
            context: .
            dockerfile: ./RoleManager-web-frontend
        image: role-manager-frontend
        ports:
            - "80:3000"
            - "443:3000"
        depends_on:
            - 'backend'